[package]
name = "ym-yagpt"
version = "0.2.0"
description = "GPT requests dispatcher"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"
serde= {version = "1.0", features = ["derive"]}